In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('C:/Users/TK\Desktop/Portfolio Notebooks/Linear Regression Multiple Variables/homeprices.csv')

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [18]:
bedrooms_median = df.bedrooms.median()

In [20]:
df.bedrooms =df.bedrooms.fillna(bedrooms_median)

In [22]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [25]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df[['price']])

LinearRegression()

In [27]:
model.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [29]:
model.intercept_

array([221323.0018654])

In [31]:
model.predict([[3000,3,30]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[530725.43066664]])